server:
  port: 8112
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: cloud-earlywarn
  datasource:
    url: jdbc:mysql://192.168.8.22:3306/jhmk_waring?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
#    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
logging:
  config: logback-spring.xml
