server:
  port: 8112
  context-path: /page
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/
  instance:
#    hostname: 192.168.8.20
    hostname: localhost
spring:
  application:
    name: jhmk-page

  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.8.22:3306/jhmk_waring?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
#    url: jdbc:mysql://localhost:3306/jhmk_waring?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
#    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql

hospital: bysy