#视图可配置文件
#广安门 视图
driver: oracle.jdbc.driver.OracleDriver
#测试库
temp_baogaourl: jdbc:oracle:thin:@172.16.254.106:1521/ORCL
#gam_temp_baogaourl jdbc:oracle:thin:@172.16.254.106:1521/ORCL
#正式库
baogaourl: jdbc:oracle:thin:@172.16.254.102:1521/ORCL
baogaousername: lcjczc
baogaopassword: gam_cdss
#  广安门 入院记录
ryjlurl: jdbc:oracle:thin:@172.16.254.13:1521/orcl
ryjlusername: emr_analysis
ryjlpassword: gam_jiahe