server:
  port: 7088
eureka:
  client:
    service-url:
      defaultZone: http://192.168.8.20:9701/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.8.22:3306/yunemr?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
#    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql

