server:
  port: 9501
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9701/eureka/
spring:
  application:
    name: cdss
  data:
    mongodb:
#      host: 192.168.8.22
#      port: 20000
#      database: BYSYDATA  #前3列作用等同于最后一列
      uri: mongodb://192.168.8.22:20000/bysyalldept

